### ISSUE TITLE
Inconsistent function signature

### ISSUE THREAD

**Issue by Ma-Weber** [eichstaedtPTB/PyDynamic#18]
The following function definition in PyDynamic-1.2.61\PyDynamic\uncertainty\propagate_DFT.py use slightly different orders of the parameters (Y,X,UY,UX vs. Y,UY,X,UX). This need special attention for the user and might be a pitfall when changing from multiplication to division.
`def DFT_transferfunction(X, Y, UX, UY):`
`def DFT_deconv(H, Y, UH, UY):`
`def DFT_multiply(Y, UY, F, UF=None):`
Maybe introduce an additional function `DFT_divide(Y, UY, X, UX)` for calculation of Y/X.
Additionaly, for me, the order of parameters “numerator followed by denominator” is more intuitive. In DFT_deconv and DFT_transferfunction the order is “denominator followed by numerator”.

**Comment by eichstaedtPTB** [comment]
Solved with commit 909da53e8a42f1bcdb408f7d517e29f8703b8d7e
