### ISSUE TITLE
Wrong comment in identification/fit_filter.py

### ISSUE THREAD

**Issue by bruns01** [eichstaedtPTB/PyDynamic#3]
In the comments explaining the parameters of the function 
fit_filter( ... )
it reads 
<cite>
justFit: boolean, when true stabilization is carried out.
</cite>
To my understanding it should read (inversely):
justFit: boolean, when true stabilization is _not_ carried out.

**Comment by eichstaedtPTB** [comment]
Fixed with [commit](https://github.com/eichstaedtPTB/PyDynamic/commit/6c8b36cc36778e63cf3506b192855787a9254acc)
