### ISSUE TITLE
Proposal: GUM_DFT and long data sets

### ISSUE THREAD

**Issue by bruns01** [eichstaedtPTB/PyDynamic#4]
For long data sets the size of the covariance matrix calculated in GUM_DFT(...) gets prohibitiv.
In many cases however, the analysis is only interested in a (small) subset of the complete frequency range.
Hence it would be beneficial to have a means to select a subset of the frequencies in a parameter of GUM_DFT with the covariance matrix only calculated for that subset.
The subset could be selected by 
- maximum frequency 
- minimum and maximum frequency
- Boolean vector of indices (optimal)
- ...

**Comment by eichstaedtPTB** [comment]
Added option to mask the frequency array and calculate X and UX only where mask equals True.
Link: [commit](https://github.com/eichstaedtPTB/PyDynamic/commit/3740d0bca9d447812a8f94975bbcff283530c826)
