### ISSUE TITLE
Transfer TODOs to issues

### ISSUE THREAD

**Issue by BjoernLudwigPTB** [eichstaedtPTB/PyDynamic#41]
The code contains still a lot *TODO* statements. We should transfer these into this [Issues](https://github.com/eichstaedtPTB/PyDynamic/issues) section.

**Comment by BjoernLudwigPTB** [comment]
@mgrub Say, all these is resolved, aren't they?

**Comment by mgrub** [comment]
Yes, the task of transfering the TODO-statements into issues is completed. 

(It though remains to resolve the actual issues.)

**Comment by BjoernLudwigPTB** [comment]
Nice, then we don't need this anymore.
