### ISSUE TITLE
Documentation: Deconvolution calculates transfer function

### ISSUE THREAD

**Issue by bruns01** [eichstaedtPTB/PyDynamic#5]
The function 
DFT_deconv (H, Y, UH, UY)
can be used to calculate the transfer function H(f) in the frequency domain by using
H,UH = DFT_deconv (Y, X, UY, UX).
Although this is in many cases a primary question when starting from calibration measurements
it is a "well hidden" feature so far.
This feature fills an important gap and should be exposed in the documentation.
It may even be worthwhile to create an additional function pointer/hook 
DFT_TransferFunc = DFT_deconv 
in order to make code more readable, that makes use of this feature.

**Comment by eichstaedtPTB** [comment]
Added this function with [commit](https://github.com/eichstaedtPTB/PyDynamic/commit/6c8b36cc36778e63cf3506b192855787a9254acc)
