### ISSUE TITLE
knowing the frequencies of the GUM_DFT

### ISSUE THREAD

**Issue by bruns01** [eichstaedtPTB/PyDynamic#6]
For consistency reasons it would be helpful to have a function
uncertainty.propagate_DFT.GUM_DFTfreq(N,dt)
which returns a vector of frequencies related to the result of GUM_DFT(...)
See also numpy.fftfreq(...) or scipy.fftpack.fftfreq(...)

**Comment by eichstaedtPTB** [comment]
Added this function with [commit](https://github.com/eichstaedtPTB/PyDynamic/commit/6c8b36cc36778e63cf3506b192855787a9254acc)
