### ISSUE TITLE
fit_sos: Consistent handling of complex inputs and outputs.

### ISSUE THREAD

**Issue by bruns01** [eichstaedtPTB/PyDynamic#7]
As an example:
DFTdeconv(...) returns the (mathematically) complex values of the result X as an np.array of dtype float64 
generated by hstack-ing the real and imaginary parts.

fit_transfer.fit_sos(...) in turn expects a complex input "H" (dtype=complex)
(c.f. devel branch) 
The whole package should use a consistent transfer (input/output) of complex valued vectors or matrices.
Preferably by using dtype complex where ever appropriate, to avoid any confusion.

**Comment by eichstaedtPTB** [comment]
Fixed in branch devel1; will be merged to master in next release version.
