### ISSUE TITLE
Error in fit_sos of Devel Branch

### ISSUE THREAD

**Issue by bruns01** [eichstaedtPTB/PyDynamic#8]
The call:
p,up = fit_sos((data['f']), (data['h']), UH=(data['uh']))

leads to errors in np.linalg.solve (c.f. below).

type f: float64
shape f: (161,)
type h: float64
shape h: (322,)
type uh: float64
shape uh: (322, 322)

h,uh are results of DFT_deconv(...)
f is result of GUM_DFTfreq()

Messages:

/home/bruns01/PTB/Python/Stoszauswertung_tdms/fit_transfer.py:60: RuntimeWarning: covariance is not positive-semidefinite.
  HRI = np.random.multivariate_normal(H, UH, runs)
/home/bruns01/PTB/Python/Stoszauswertung_tdms/fit_transfer.py:105: RuntimeWarning: divide by zero encountered in true_divide
  iri = np.r_[np.real(1 / H), np.imag(1 / H)]
Traceback (most recent call last):
  File "/home/bruns01/PTB/Python/Stoszauswertung_tdms/Shock_PyDynamic.py", line 177, in Identify_total
    self.Identify_singles()
  File "/home/bruns01/PTB/Python/Stoszauswertung_tdms/Shock_PyDynamic.py", line 262, in Identify_singles
    p,up = fit_sos((data['f']), (data['h']), UH=(data['uh']))
  File "/home/bruns01/PTB/Python/Stoszauswertung_tdms/fit_transfer.py", line 112, in fit_sos
    XVy = (X.T).dot(np.linalg.solve(W, iri))
  File "/usr/lib/python3/dist-packages/numpy/linalg/linalg.py", line 384, in solve
    r = gufunc(a, b, signature=signature, extobj=extobj)
ValueError: solve1: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (m,m),(m)->(m) (size 644 is different from 322)

**Comment by bruns01** [comment]
You may have a look at the "data" by unpickling the attached file:

import pickle
data = pickle.load(open( "data.pickle.zip", "rb" ) )

[data.pickle.zip](https://github.com/eichstaedtPTB/PyDynamic/files/536092/data.pickle.zip)
Note: The extension "zip" was added because github needs it. This is not a regular zip file.
It's a python-pickle-file

**Comment by eichstaedtPTB** [comment]
Fixed with latest [commit] (https://github.com/eichstaedtPTB/PyDynamic/commit/ad4fb7a23f4881971f89b2a831e694880dd87ce3) in develop1 branch.
Together with some other bug fixes for that function.

Regarding the RuntimeWarning "covariance not positive semidefinite" you may wanna try 

```python
from PyDynamic.misc.tools import make_semiposdef
newUH = make_semiposdef(UH)
```
