### ISSUE TITLE
VisibleDeprecationWarning 

### ISSUE THREAD

**Issue by bruns01** [eichstaedtPTB/PyDynamic#9]
PyDynamic installed/updated via "pip" on 18.10.2016:

/usr/local/lib/python3.5/dist-packages/PyDynamic/uncertainty/propagate_DFT.py:594: VisibleDeprecationWarning: using a non-integer number instead of an integer will result in an error in the future
  rH, iH = H[:N/2+1], H[N/2+1:]
/usr/local/lib/python3.5/dist-packages/PyDynamic/uncertainty/propagate_DFT.py:595: VisibleDeprecationWarning: using a non-integer number instead of an integer will result in an error in the future
  rY, iY = Y[:N/2+1], Y[N/2+1:]
/usr/local/lib/python3.5/dist-packages/PyDynamic/uncertainty/propagate_DFT.py:597: VisibleDeprecationWarning: using a non-integer number instead of an integer will result in an error in the future
  Yc = Y[:N/2+1] + 1j*Y[N/2+1:]
/usr/local/lib/python3.5/dist-packages/PyDynamic/uncertainty/propagate_DFT.py:598: VisibleDeprecationWarning: using a non-integer number instead of an integer will result in an error in the future
  Hc = H[:N/2+1] + 1j*H[N/2+1:]
/usr/local/lib/python3.5/dist-packages/PyDynamic/uncertainty/propagate_DFT.py:68: VisibleDeprecationWarning: using a non-integer number instead of an integer will result in an error in the future
  v1 = V[:N]; v2 = V[N:]
/usr/local/lib/python3.5/dist-packages/PyDynamic/uncertainty/propagate_DFT.py:69: VisibleDeprecationWarning: using a non-integer number instead of an integer will result in an error in the future
  w1 = W[:N]; w2 = W[N:]
/usr/local/lib/python3.5/dist-packages/PyDynamic/uncertainty/propagate_DFT.py:83: VisibleDeprecationWarning: using a non-integer number instead of an integer will result in an error in the future
  A = M[:N,:N]
/usr/local/lib/python3.5/dist-packages/PyDynamic/uncertainty/propagate_DFT.py:84: VisibleDeprecationWarning: using a non-integer number instead of an integer will result in an error in the future
  B = M[:N,N:]
/usr/local/lib/python3.5/dist-packages/PyDynamic/uncertainty/propagate_DFT.py:85: VisibleDeprecationWarning: using a non-integer number instead of an integer will result in an error in the future
  D = M[N:,N:]

**Comment by eichstaedtPTB** [comment]
This was already fixed in the latest version of branch "master", but not yet pushed to PyPi. 
Should work now, after upgrading to 1.2.4b0 or 1.2.5
